name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Changed from 8.0 to 8.2
        extensions: mbstring, dom, fileinfo, curl, json  # Added required extensions
        coverage: none
    
    - uses: actions/checkout@v4
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    
    - name: Install Dependencies
      run: composer install --prefer-dist --no-interaction --no-ansi
    
    - name: Generate key
      run: php artisan key:generate
    
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    
    - name: Execute tests
      run: php artisan test
